version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
    - echo "Installing dependencies..."
    - npm install -g serverless@3

  build:
    commands:
    - sls deploy --stage dev

  post_build:
    commands:
    - echo "Updating resources..."
    - echo "DONE"
