version: 0.2

env:
  variables:
    STAGE: dev

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18

  pre_build:
    commands:
    - echo "Installing Serverless CLI..."
    - npm install -g serverless@3
    - echo "Stage set to - $STAGE"

  build:
    commands:
    - sls deploy --stage $STAGE

  post_build:
    commands:
    - echo "Deployment to $STAGE complete."
    - echo "DONE"
